### ISSUE TITLE
Which tool  is used to draw the Architectural Diagram

### ISSUE THREAD

**Issue by blling** [hdimitrieski/e-shop#14]
Which tool  is used to draw the Architectural Diagram， could you upload the diagram source file to github?

> I am sorry use the issues tracking to ask this question , but i really did not know where is the right place to do this

**Comment by hdimitrieski** [comment]
I use http://app.diagrams.net. Check out the following. It is a copy of the diagram for this project: https://drive.google.com/file/d/1IKX3fDDKn1TDtGpvp5nFhhYqwKH0cruA/view?usp=sharing

Maybe the [discussions channel](https://github.com/hdimitrieski/e-shop/discussions) would be a better place for questions. :)

**Comment by hdimitrieski** [comment]
I didn't know that. Check if you can open this [link](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=e-shop-architecture-shared.drawio#R7V1Ze6M4Fv01eXQ%2BJFY%2FJk6qu6erq9OVmq%2Bn5g3bxKbKNh7AWfrXj8TOZRVGjhwrqSXISAgizrn36i5X6mz7%2Botv79d%2FeEtnc4WV5euVeneFMVZUg%2FxHW97iFmTqKG5Z%2Be4yacsbHt1%2FnKRRSVoP7tIJSieGnrcJ3X25ceHtds4iLLXZvu%2B9lE978jblq%2B7tlVNpeFzYm2rr3%2B4yXMetlq7k7b867mqdXhkpySdbOz05aQjW9tJ7KTSp91fqzPe8MP5p%2BzpzNvTppc8l7vep4dNsYr6zC2s6ePMf9HmQMzb2wlmT%2B3Z88Mi0L%2FY2uc37SbD29rTxEITe1vHTU7697ZNTHkh%2Fb5e23znBwnf3oUuaoo9vSp0V74n%2BptYO%2BddJxqYdN%2FacrJCowxU2NmTit0%2Fejk4zCN%2BSZ2787%2BClH0yCaEXQwZGxf80%2FJD%2Btkv%2BjUeZ5g57cGNbTD8lDmcMOpC2%2Bcrl56T5nTXo8WPQIyGD6XaFv8bx0Cn7bYKx3i9ruNhll4W08vzTKFVYX0VddX738ays9n7pnAW8TF5bfw1%2Fb1Q%2Fzvxs0uf%2Fr3v%2Fy48vybTNB2bLOlmt%2Bo3gdbumvHiXzT951RI%2BXdrB26MgKOXhZu6ET7MmqJQ0vBFdoB3ezmWV3qyqW%2BsnUSXsQ%2Bt5Pp%2FiJoSJ9llyi0P4UfdEeazta0dvXFYWs64V2vY9WNpn5rb1xV3Q9L8g7RZaxert1Qvt%2B6YbJvPeeuwujt0iny0O5Jo9wpkR%2F6eqYkTZEj5L2cptZbkwaEGisa8M1jbVDlq9N%2FsR3cGeHNp20eZsvi3RdZ8uELLvi5w65a3u%2BKZ%2FxZG8C58q8o3%2FUW98h6zU6J%2F7FVREpQZpnxw%2Bd10JTskZ%2BcQhahP4bOSX91EjQMuGLCdaShpccfXGKsesi8lpJo52g3CobPAdF8kOyMtPDBCaPgEyIk49vQehsHxfe3rn1DrulnUyBnHSz32%2FchZ2D5qP3FL6Q50U%2BjbudDiULCFUzKvl1hZPkbaDDbpynsAFSqlhbA3usCDx8SgloFx91K3Z3ghpuBTWf%2Fooj6KrDtQjKHstQVoDBDPboge0vkq5YAYi383ZOHdgZ0VcV7OIv0h4tpFt78XMVzROMl6Jd9CTVW%2FqWkke2uUma515I2DwbxfPJ6wBnRG7N3a2%2BkfcghoCkgd6Sktzggx0SLKUDWuTRaVVQ9b3QDgswQuDYJadQ%2FL3zyQtp71Yb5yFvvN15n5MXREln92Avl%2FF1lejGNt7LTSr90ZZEPCxcxXnd27uUcshlDn7gPjtfnfhVik9JIbAA%2Fo5%2F%2F%2BzEHBBdaR54m0Po3GS%2FPMQXcysMhKsUVEdLGVdUeQnXkZUQBFZow2VWG4FqJqZRQy1ZY4lbTHwScimQiEsX%2FeSBaidYKYFZfOqMvPG2u3PiNx7nh%2BlMyWjOYr0j7%2Bsq4dKb3eqwsX36VLHy1bHpbBqE%2BQffe470LnLHEeIVxPlMVXg67Ba0C4GR8C3SywoqAO367NpxL5dO68UhDKDM6Uvp%2BNcnVQdSCZ5Z9C88Vj26rGFvKYbv5sE%2BGzx%2FzOejJNwb9PtdlAS1lU9rxHOycG7jVVNY9F3UOo95%2BfM8bciJOiONRmIE2gZC1s3sDtA7btExKmpEVU25N%2B9uUvF8iIIxHLTHhuLzUjBUXFYw6tQLrY4CjBOrFzcPv5GWX%2BzQebHfqgRRQKZ6tH%2Fc%2B1QgwsottTBFmJ81zTbeYVkdvY0G4uk8eX7GA40UdVps52LqiWYh0X0AumsM2lIHhENligmzsXqD76YsGJ3rX5Hq0huyT4h%2FUvgfS%2Fi3rDINZLTQyQOn0QRyHviTqt2k7YsXuk8JwgbH80E34vuOvZmELkVXZVe%2BuGIT8SrMmMBLprj3vYUTBBL%2FLxj%2FdYn%2FEv%2FFx3%2BEDCQ0AeTI%2FtXZxLi7dvdN4P53ZFt59BY%2FnWZsJxQRHLYRtkM8f%2FK95q2HY%2FcI2EZJ3see6N8IZnUkUIPFR88qJQ4mmmBGVaMVVZ3dMjJ2k6P5hqyBb2t31wylShUUNYV%2BZ6CXOjrQnmTsT%2B4mHacCiham3%2FS8zTyaQLqJUMVJMlI6BS0ayvbDYsOPw3b%2FmNwUweK0JTmD7nKUTTjOcuWk53t%2BuPZW1BR5n7feOq9u%2BJ%2F06uTn77TndbRvTA%2FvXtOR6MFb4aCw2dBmLVo6T%2FYh%2BoWS1eG%2F%2FScaXk8Pv6cD0oP8WtHRW%2FEIXq0R3gLv4C%2BclmWixueRJ7tywi6Sxgp9gn3AckLuSjOa4dGPEOq57DFTB4%2FJFR4ojeXDm2DPV1MBwsb3nfQqusSAgRACxp2K0SZ%2BMi0jpSd6T0%2BBUzongvTs2Yxv7jmQFewTto%2BhTHl0%2FGeX%2FLLZBf3fnbfFxrN%2F9pHxyX%2B7MLbe080w8u%2BCSvBX1H1pZ6%2BcrRM9lZKlX4r3Fyzem1K8l%2BK9%2BOL9RHDzDpt0%2F%2Bu3bw%2BxBd%2BjNIEbkZ1%2BSgGdCPYRvL%2B45GalWC%2BsWG9Jsf4IsT6V1r%2FncjeTVD%2Bq0N6pIvCX6s2eUv2YInwqspsDRfZsAk0DNUjsnKXx37ZE%2BA2i19Hzhwjhf%2B5crxGm%2F0znkow%2BiyzpdtYSZOJ4QLSAWFBPJiQl70uVvKdS8paSt%2FiSd%2B4qmSChYYklegOQv4q2LV%2BHeNi421Wpa6uhJb8WNbDEO7HSrCLBPQmcUiS6S3Q%2FQ3T%2FCIaVBvT%2B6tjLougtN0kFt6ag9vBTaU5h2SXFHHZJ%2BZtA0qwBDDubpmpYzRB25NamrpbhUkcD7SSm2TGQaDubQ4D406Mq0fjDoDGWaHwEGucG7e8FbP54xu0UxzqhfdoT2TmgODKnAH31gTCOFUgIcCTRcLxqLgkGe6Ywu6CnVpPDfuPZS2kxkRaTHDfaw0ilxURaTMSwmGjaxVhM%2Fh3BdElKDz0powsso7dHa0oZncVicp4GE5XZYGIYhsnNYALjMise3B%2FXF3xsi8lj6koiwfg8wLg9dFKCcZfBxIpSnmUmk2tFsZghOTObEKBTFPWqaDm5VlXtSjDrSV%2Bc72s9yWFeVQ3MDeZRZvdI7SAwe2NvnK%2FYZuBInTj%2FVnsTJ7evpIH%2BDwUXEf4mFhC7Lx1TpJmlBDDtkafSzCLNLEKYWaAfubhehw%2F2WxJVyduQ%2FuhuD5skEogmYgzc7X4TOSFmU1jFCcAkxF8yxMuYTgnxZwDxMKZTXIifkaVF8Ie0zrztNorkORbiaYjQzWtL%2BY2GVI1RGH880CKbFXmFtzKW6JIhvz3wVEK%2BhHwxIP98golyzP%2Fr4PhDwolGQnyf3KXrPEvMl5hfxnwZQCox%2FxwwX1PExvwc0qNKMKTtMfQdexsj7sPGDgkQb9Ozh9TpIO9dlFf3d%2Fvpp92I%2FycFc1lBQyAoL5SPbCuhsXjbuATTfbqLmVQ1Qnr0uGhVpXgdBd6BvlOnrKZRwn9ZTeOsq2kgYHZHGXgLAta5gH5rB4XkuDy3VOfJlWQORQnftfDdHqcqJXEpiQshieuG2IJ4IXkuQdW30F2MUBdjlsvdiVyf2le6gd%2FOp1FXISPyxdxlbUFU8FUywSUzAZZMIJlAfCaAXvmiMUEO93RpEfk7c6oZYH75w9utvLvbRsDP%2FOrLxnXynxNXBpZ2mUuF836lTZvsMtIGI20wY2ySTlWJzgkYU2HbJ%2B9ELOG7O2qZL5TRliB9gSDdHvMqQVqCNA%2BQhruaHxqkH7wgXPnO41%2BfB0jREqUlSk9wezCsRGmJ0jxQ2rogkP5KnnHQjc%2FZbqbEZYnLE9weDypxWeIyB1yGO5FTYXNonVh4TqP3JTZLbJ7g9kBOic0SmzlgM4y8Fxeb69Jq1ZbQpHWYY4eOtBryxRbSZAchYWtaLo25odMMU2JnsSqm%2Fc5SVg3MX4WuQP4q44pH%2FiqA7gSy8WLRhi7dea2Skgyj1bxMwIqAMtL4ZS%2BcGGArbnC9h4lqdYwkWvrC3Bvvv%2B7%2Bp5vFLTK44pU7tnnaLV3yervzQ0hesXiLTyauksJwiYdkuKN0rQNtIrrWVTYGhQuhYctL%2B6%2B721kjgqdFfOLaPUmN4xffDWV6WuHT06rtQYcyPe0Z1fM5QjA3egrm%2BD2q0SeYqgKThKUNlMJ1q2Og96lOTwTpJ3eE7LA01iVrmm28A4Xj8uBtQnhw2O%2FJor%2BqyTVFoMvxqRT%2BTySgL6IxD37EHlIsv2CxXJWxj1IsPwOxHGFYiEI0sTyng%2FvPvw%2FggvuNHRApiVKAQ5b2OqaDz96KCEVBcvS7OyeY3ocLYg%2B%2BKAAycANpiZGQn0M%2BlpAvIV98yK%2FE0QgH%2BdISIy0xFFDbwwylJeYiLDHpid2WGOP9LDEGKFtvmQMtMVPUMdApLTEj4vDfEnLPAnLbgwYl5F4E5Pb2SsF9q2py8UEBztLW0NJqEw13jHSmoCuF3zNG4vbAQInEl4HE075IrL0jEqtjSb8TpH5M8beMxBJ1hUXd9rA%2FibrdtYmLxeKPrE08BvbyLErcG5z1dwRnBCoQW0MrzU87xmmAZvLC2G%2BF0xJDfvOEsYLKF0puoGle0AmmfDr5IZ6BKDzRXuzg4TDfuME6SbNK5fUFGe6wzVM9Nefdk%2Fzx%2FvzRHpoo%2BaObPzDgj6Nkd1UtlbbP4oREYZDehhalJ4Nk8T%2BKoSaz4EEqlS1ENNT1cKIBMw5S4SbjWMSiQzOP1k4slakxd0C4owd0vmE9X9NayO7dQqQkIUpCTAlR2DDZcyFEbBYIUbmeTtPj%2FoTIk8FMbgxmWpbOj8HQWASG1a6RRuIvlOqbPdkINTj19z0%2Fu5HmDqi1g2QjyUaCsVF7sKxkI2bzHjrCvEdTN0TZcAqpG3QrM%2FmJoqP1jgRjZzgN8WM4Ddr9lKEEB2vfqT23x1kJTlPZCE5X2AgOno8Uq71D5c5BB0lwkuDEIjhNBi%2BPvX%2BlDSe47CDmNiU3RgrCbf19a9ntj1YcD8OF26yKzgVthn3JDaYfQhon66Ops5GbxWishOd3mhI1SG7MHdKwEcmGkg3FZMP2IGzJht3GR6PAhsOMj8XdOCy0PwfG3NhQVXV%2BbDg1IZJPR2NDnQ8bIsW0mOgNIca9uEqHLNK9kd8qm3GsHVIF9uMS4qxKf9KnUXQWxJIFB7BgJ9EUiM0wzKOJbThv6dxoSzNSv3IOtEV0tjJ%2BahoYozdtmSYAYlPnQ1twypmzSqPNEaplzB20D29zlKRyhqQiY%2FMHqVYFztCtImfwcU1MVbmiI%2F73hLJSR8v%2BqtwRqlVvV%2Fm%2BHMXHVb6slBAemQ5jJGMKUfxopxCB4Pxfj39%2BIRf59du3h0ZQTyOeFkmaRYnooiO6sKH%2Fc0undghBEb2AsMWtI4KwJvvWEawwYS2cqMKECFav1J%2B8v%2FpABHN%2BPuioEvgzdA8IqdBUpEFfibH0BxVI96aBzl64l2zwEdlA2PQDZ8EGyjUyoCPBUVsnSVxUwZlAyUxOLBrDOxAMUrkRjKqmSb94EIwKc3HBzZDeBKNDX7ye2yp9GICZg%2BC2RWp2a5w97DDFLRYpSUiSkLgQkrCZGYQmpMF4nzOZYaR6TMJkmYvcwJDcshPAtRLduoD7Jex8pKgci%2B5V1JSKTWm4wqNCj4FTEhJUioyOfffK9I22LZIzIaQ%2F7J%2FRDsjNw2%2F0BHuzka5lItNRR6KHAjAnSdrLyF0gpgI2mhX%2FqB9OGL4lBGAfQo805UD%2F2fP2TaxkKvS7wme4ynzZmUX2SSa9tIN1lrP%2BdMnfmclgrLRvHNUgrSfrpDkhmFI9aCU8nFgVEsq8oY4tOQU2wPWhRje4k66PyEAS8iXkc4D8jlQGEvLPEvJPgOjTnojOAa8xLNQ9NPtbJbeN0ROwJRhLMOYAxh2R%2FBKMJRi3Jqx5DzCGeZKHg7FZbwCRWCyx%2BPRYrHcEnQ%2FDYgnFHx6KBxRsGguKNXUkKEZIisUSioWB4o6I52FQXA3blVj8wbAY993r5IHF1khYDOVricUSi98Ri7EUiz8eFAuwQ4jx%2B2G1Dpzu9aE%2BKCaIkDLErfRUAeKbA3m%2FfPLKRXmBFgsnCKKnTR72JeIxOzIKGzy6NOaGHuW8EdCXr8AC0%2Bm0xAPXGuITQAr9B5%2BecOQ%2F2IhynejV1%2F5acG%2FgmAfcArKnagyM%2BITpZtSeeMbqLdc04d7zKp9%2FFhFHEoDHBmBhYz3FBuBaGTITG4dlwFYy4E4D8zNof18kH6%2F%2BHTPk6zTtKi%2FIV0Ewjja0WikyOwYarSIejNg5w8SbEsPHxnBhIzTPBMORUURxCsXsGVFYkoQho5TwhQrxg2R2DkDet4gPI5BPIo8abjgOw2GgE0RvbwrgI9c3V4tE2gtBWmFDD8VG2hT6UFXIzXNfcUl3RcG2XDZtSB3q8YE2tdyOLzGrusovEn4KA%2FQGS8zQGNFzg45VYq5MuCt5PvRtZjw%2FvQ8pkF8yTQhb%2B1lsmmgRyI8p%2FgwYx%2BRTV4wDR%2FAzpGuIH0doowUGwogVTgVZDJh9GEkMlxgubLniM8FwVU2NKKncrR4B4VXFYTos7dV7WMf71o0cEJAyGmgD52VdHQra0J0aDjQSaMNUIRpu2c2UgPwBAFnYir3nAsh4CoRqnErZxwvV%2BFyE6r4pn5hlag2ZKjeZ2jKn1NMn%2B9LLRged0mv%2BpYGaF4ONMu%2BZnBAm9cXTdkuMAWrQs56f3qwkkA9KIEZHcKIkkE6Jvlg4YpKVseW2T1rxbaS14sTYJ%2B2byZbd4UU1eGZKR9RjqQR7Q4vBV8iip6DPhSx0DMDf7AB%2FMHnW81XBtA0ZRPThg4gMLgGdMogoDiIaKSZofA1oOEf1pSiNlaIU3eKXVlAH9iM8lJ8sWKCvZ2YUVu6BxdC7iqcjRWntcBbbDTLR%2BiUwDhZVYRI60XqxDpRWYJNi%2FvQh%2BdKBKpTvhwhe9aP3NjZrlnWigWKLn80NIUBFplZrhGNWnLAKigtiXhFiQGsxDTZnJlDeo%2BZOWOqBSCqTVPZuVCZsnPEFUdnwCiSlKLlygfVrNMyDeDif9d7OH1A1RONZxQoBTcXUR%2BIzSyvzGa%2BiiTDlRBefwfOR0lVPBMGa6%2Bw9NHR%2BYdWSAy%2BBA4UN9T4PDgT8x17EsYn%2FyvSGy%2FRWKJIliF2xd4zggDLBmsbRLxmyx%2BDYFeiaMEJN934e0F2EB8%2FP2KnZGGkd3UOT9ktJeEISnrBx8WdBeJn%2FRYH02OPiO0kP2DWFY7u%2BqU0G1Cy20mpdPNgOGC%2BtwX4e0KMbcctuAnUpU2%2FPaFXpgFAHQSIFUjd7D82QfCf5TkS%2BEzY7wbny3Xg6HqONUyuTopEnjDmRjdPixnqapfHbs5vATFymNZKNE6QKQzonG%2BdEY9T5Kh0QVrooDbrGsPfQ2gotvxsJfrG3ycq5c4OFR1DmrcqPM4JqtrujQF1Pjo97391Rwrv1CIxjMhHl%2FuA7P%2B1GqnzwvWd3GTvmk79f7x%2B%2FXaWOlU%2FkRSdvnOM%2Fu%2BSVoyt85RKAtGM2Uuzdkvz7vwOZKrnodSO%2FUiyuJSH6wSSI8I9yEDL2r315MXpcnYQYX7mGEQG5RT54ejyLAXQ399suwvoUUNtTSEZZZDidn6jeG%2FS7rm%2BbIFH3jNj5uz1tRM5rlCdf1m7oPO7tCMZffHvfTOWomX8Sr0vAWli9wXfTqgDwFH2R9kTmuUsEHtLgL4qCQ0UAUO7Nu5u7KttzdOn0HbIconNiMkyAl1xIp2s2ClnDMyX6S9fmLGqsazOrjYgepSOUG%2BvaTL1uSFRzbdiGaxprh6y5tgImqd%2B1yQRUJHNeC02NHI5gwoR8w6%2BO0teOu1qn14IpHIqUXqIG4ZQhitr0SkQo8qQWJLAWJGziBgvPVUPUMC%2BGjGojuMg3BB8c68641B1rqR2n%2BfR1mzfYs%2B6ouslN80E6UAOs4anZoBsgp9xsFR7RulznYYdOB0UTt3YQRG2RdHXBdCVsWouPQlcWLhHWcYmIqEOGWqQtaq5DgzIRjc9dfXNbsFMXldz5UZemlKN3B2eMQ7pRHglp9YkzxmYyNdmpghmoWyaqHNdh2rVvZUDf%2FIvZtpLUdx7UZwqbkOPDUJ8KqY99R6tUt8CoUF%2Fmrvi%2B1Kdxoz51ylNrgz75w6uPV4xylcjpscgOegDqXVoYVE2ZO2T7T813X3H1P8PKOJLuPjTddSTwkHR3HN1ReitVYyP0x8x2TcxUYEGzHIGGhpLgcLLr7Z3BznaGkQZz8fDO0KB3BrQs9i%2B4BkZCJjd%2FDBg20KGpVTog3EF3U%2BhRz9zB7KLHxscl6VHSoyD0iCU98tUGp1OjTI%2BYffeuBz%2FqVslAiooxbSfix74%2B%2B0P4kWOE9gTp9VwzgB8hCenpQxndab8SVme18yPsgFCX7VOpuPkz9zA6EjxWHxjoIRlSMuR7M6SwSUzOmyEbOa2gWKaa5GDFskCQmp4x5veEmLOGExFk3xDuAQSp86vzWnXuH8vFJd8tGzuCW2HTHuH5mYG4mergrbD36CpySJ77tLWHJEdJju9NjsJmN%2FnY5EjZq1xgl0Y1H%2BNfE5epKbLjIPeaI9ixb4KvAexIuZ8XPeoNXDOAHk2A9zqczVgZvWCwWwc9VjYGUZflE1UIlbmHgTp6VB4X6CHpUdLje9OjsLlQzpseW2gQs9NgD%2BsqVko%2BOJluejp67J3PeQA9qogfPVoNXDOAHivB4JwiJKyKbbU9IQo8v9NJFNpimTsgvcsUa2hQlmDvIaM2JJ2KRafCplo5bzrtNMUCTfMoO6xiljYqKYWfmkoxPypVqjV6%2BGWShvkv%2B1MpArUQKrEfY3mtIotN1ax0QLreRVyVm2mrKSpAlpT7SbD29nQGyy1BqAqxkZUeeFl7tSLpLu0aZzSJMp14T3RBr2mqEycZvoHHzialyZmkLllEX3V9uacuMdtTl7QkJskKvlEkjZKaBOWkJoASFEv9ZOp1zKcQ7UGfVbk0y1oSrO1oYW9fV2To9fVCu95HC5y6p1RSmgCyrKQPaUoKIkT%2BDz3NtXKi5CqNFNg%2Fqwg07U0ytioyWGqbKyUVgYqcCElFWgX9fweOrLUpsngvcA4R%2Bn2u4j2HHCK4UiN6WGG04UJ87%2FJmbCL8RLlGqslPiFdViLcDZXjd7BhoLFcKo%2F46TfNSp7jtfEGEcckql8MqAqf6kKxSYpWkvMvxkc7DacXsXWZFMF7RrOvUvzBFXn0gtWjABKPyYRajonq0Mwuc1umZhRz6NDltoTdVaf%2FwlhT37%2F8P). app.diagrams.net allows me to export the diagram as image, HTML, XML and PDF, so I can't get its source.

**Comment by blling** [comment]
OK, thanks :-)
