### ISSUE TITLE
com.eshop.gqlgateway.types package missing

### ISSUE THREAD

**Issue by akpatil** [hdimitrieski/e-shop#19]
Unable to build project as classes from package com.eshop.gqlgateway.types.* is missing

**Comment by hdimitrieski** [comment]
Hi @akpatil,

That package contains the classes generated by [dgs-codegen](https://github.com/Netflix/dgs-codegen). Basically, when you build the project, the plugin generates the types specified in the GraphQL schema. Can you see any errors when you build the project?

**Comment by akpatil** [comment]
Okay. Ill retry and let you know soon. I was unaware of this.

**Comment by akpatil** [comment]
I was able to generate the java files after building the project. Thank you.
The files get generated under build / generated / sources / dgs-codegen folder.
If i want to resolve the compile time errors in eclipse; do i manually copy the package into the project ?

**Comment by akpatil** [comment]
Thank you for your prompt replies. I have copied the types manually. Closing the issue.
