### ISSUE TITLE
API-GATEWAY status is always DOWN.

### ISSUE THREAD

**Issue by blling** [hdimitrieski/e-shop#8]
![image](https://user-images.githubusercontent.com/26540808/177100506-8d920ff9-fc86-4747-9c12-ef6475dc7a6b.png)

 `./script/startup.sh` and `docker/docker-compose.infra.yml` startup `gateway`, the status is always `DOWN`, Maybe something wrong?

**Comment by hdimitrieski** [comment]
There is a custom health check implemented in the API Gateway: `com.eshop.gateway.config.HealthCheckConfig`.  The status of the API Gateway is UP only when the statuses of Catalog, Order, and Basket are UP.

**Comment by blling** [comment]
![image](https://user-images.githubusercontent.com/26540808/177120073-588c0e2e-097d-43fa-820c-5006654c26fc.png)

All up, but the `API-GATEWAY` is still `DOWN`. Maybe the `/actuator/health` of `API-GATEWAY` should skip auth?

![image](https://user-images.githubusercontent.com/26540808/177120620-fc0ca223-a5c7-4551-a85b-7650ff87e356.png)

**Comment by hdimitrieski** [comment]
The problem was that the web client couldn't resolve the URLs of the microservices relevant to the health check. Adding the `@LoadBalanced` annotation fixed the problem.
